# Copyright 2020 Hewlett Packard Enterprise Development LP


# Dockerfile for running testing coverage on HMS BMC network protocol pkg.

FROM cray/hms-certs-build-base

# Run coverage.
RUN set -ex \
    && go test -cover -v stash.us.cray.com/HMS/hms-certs/pkg/hms_certs/.
